[package]
name = "scbuffer"
version = "0.1.0"
authors = ["Eirik Blekesaune <eirik.blekesaune@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rosc = "~0.3"
cpal = "0.11.0"
